# Generated by Django 5.0.2 on 2024-03-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_alter_student_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='project',
            name='portfolio',
            field=models.ManyToManyField(to='portfolio_app.portfolio'),
        ),
    ]
