# Generated by Django 4.2.11 on 2024-04-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pictures',
            field=models.ImageField(null=True, upload_to='recipe_images/'),
        ),
    ]
