# Generated by Django 4.2.11 on 2024-04-26 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finalproject_app', '0002_alter_chef_phone_number_alter_recipe_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
