# Generated by Django 4.2.11 on 2024-04-27 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject_app', '0005_alter_chef_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finalproject_app.recipe'),
        ),
    ]
